server:
  port: 8050

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: NotificationDTO:com.ltineraryplanning.tripservice.dto.NotificationDTO,EmailAndFirstNameDTO:com.ltineraryplanning.tripservice.dto.EmailAndFirstNameDTO,SendDestinationInNotification:com.ltineraryplanning.tripservice.dto.SendDestinationInNotification
    consumer:
      enable-auto-commit: true
      group-id: test-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:5435/trips
    username: ltineraryplanning
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: {OPENAI}
      chat:
        options:
          model: gpt-3.5-turbo
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      qdrant:
        base-url: http://localhost:6333
        collection-name: suggestions
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:trips
#    username: sa
#    password: admin
#    driver-class-name: org.h2.Driver
  data:
    mongodb:
      uri: mongodb://fenil:1234@localhost:27018/tripdb?authSource=admin
kafkaTopic:
  trip: tripTopic
  createEventTopic: create-e
  deleteEventTopic: delete-e

application:
  config:
    gateway-url : "http://localhost:8222"